Public Class sendfrompic
    '8 BIT ASYNCH (FOSC/[16(N+1)]
    'BRG16 = 0
    'BRGH = 1
    'SYNC = 0
    'BAUD = 9600, ACTUAL = 9615
    '% ERROR = 0.16
    'SPBRG = 25

    'BAUDCTL(BAUD RATE CONTROL REGISTER)=00
    'INTCON= HEX 00
    'PIE1= HEX 00
    'PIR1= HEX 00
    'RCREG=NA
    'RCSTA(RECIEVE STATUS & CONTROL REGISTER)=80
    'SPBRG=DEC 25, HEX 19
    'SPBRGH= ?
    'TRISC=00 (CONFIGURE AS OUTPUTS)
    'TXREG=SEND "$"
    'TXSTA(TRANSMIT STATUS & CONTROL REGISTER)= HEX 2E

End Class
